### ISSUE TITLE
[BUG] in GET "/v2/entities/<id>/attrs/<attr_name>/value" if the attribute does not exist in the entity not returns the expected error description

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1890]
in GET `/v2/entities/<id>/attrs/<attr_name>/value` if the attribute does not exist in the entity not returns the expected error description. 

Assuming that the entity "room_1" exists.

#### GET request
```
GET http://localhost:1026/v2/entities/room_1/attrs/dfdsfsdfds/value
Content-Type: application/json
Fiware-Service: test_attr_attribute_name_unknown
Fiware-ServicePath: /test
Accept: text/plain
```

#### GET Response 
```
http code: 404
date: Wed, 09 Mar 2016 14:40:23 GMT
connection: Keep-Alive
content-type: text/plain
content-length: 95
{"error":"NotFound","description":"The requested entity has not been found. Check type and id"}
```

#### Expected Response 
```
http code: 404
{"error":"NotFound","description":"The entity does not have such an attribute"}
```

**Comment by fgalan** [comment]
Already fixed (.test in PR #2317). Pleae @iariasleon have a look and close it if you find it ok.

**Comment by iariasleon** [comment]
LGTM
```
`http code: 404 - Not Found
headers:
   date: Thu, 21 Jul 2016 07:58:32 GMT
   fiware-correlator: eae3ddcc-4f18-11e6-b8c2-005056a20feb
   connection: Keep-Alive
   content-type: text/plain
   content-length: 79
payload: {"error":"NotFound","description":"The entity does not have such an attribute"}
```
