### ISSUE TITLE
in POST v2/subscriptions in notification/attrs the subsc is created if length max is exceed 

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2100]
in POST v2/subscriptions in notification/attrs,  the subsc is created if length max is exceed 

#### subscription request
```
POST http://localhost:1026/v2/subscriptions
Content-Type: application/json
Fiware-Service: test_notification_attrs
Fiware-ServicePath: /test
 {"notification": {"http": {"url": "http://localhost:1234"}, "attrs": ["1qjl20ykDivIDV36h7NihyKeoZuYkharqHqTDcCvQF8pRdzyAyV92XAiecCjMGZ1WU07Xh2ZxGZwUTfYXfLDALPAabJqGpgsOB1rkQgcNZIBHe9GA3yI9Ob7PxUjmshBSGer0jVfJOwXWVXnDi0hF5hQtpZPaHDnRPVuXzEpZetiNGHx2rZmHPmMeJpM4C8pjzz9ouknCDV4g7falWPdjbglbdtjRAemcYBOzS9yOX0MTItxuj5xtzPCiGLIa7W8E"]}, "expires": "2016-04-05T14:00:00.00Z", "subject": {"entities": [{"idPattern": ".*"}], "condition": {"attrs": ["temperature"]}}}

```

#### subscription response
```
http code: 201
date: Thu, 28 Apr 2016 08:18:24 GMT
fiware-correlator: c6c64362-0d19-11e6-a63c-005056a20feb
connection: Keep-Alive
content-length: 0
 location: /v2/subscriptions/5721c9425d8f03a5174e8f1b
```

#### expected response
```
http code: 400
...
{"error":"BadRequest","description":"notification attribute name length: 257, max length supported: 256 "}
```

#### mongo docs
```
{ "_id" : ObjectId("5721c9425d8f03a5174e8f1b"), "expiration" : NumberLong(1459864800), "reference" : "http://localhost:1234", "throttling" : NumberLong(0), "servicePath" : "/test", "entities" : [ { "id" : ".*", "isPattern" : "true" } ], "attrs" : [ "1qjl20ykDivIDV36h7NihyKeoZuYkharqHqTDcCvQF8pRdzyAyV92XAiecCjMGZ1WU07Xh2ZxGZwUTfYXfLDALPAabJqGpgsOB1rkQgcNZIBHe9GA3yI9Ob7PxUjmshBSGer0jVfJOwXWVXnDi0hF5hQtpZPaHDnRPVuXzEpZetiNGHx2rZmHPmMeJpM4C8pjzz9ouknCDV4g7falWPdjbglbdtjRAemcYBOzS9yOX0MTItxuj5xtzPCiGLIa7W8E" ], "status" : "active", "conditions" : [ { "type" : "ONCHANGE", "value" : [ "temperature" ] } ], "expression" : { "q" : "", "geometry" : "", "coords" : "", "georel" : "" }, "format" : "normalized" }
```

**Comment by iariasleon** [comment]
the notification exceptAttrs field has the same behaviour
#### request
```
url: POST http://qa-orion-fe-02:1026/v2/subscriptions
headers:
    Content-Type: application/json
    Fiware-Service: test_notif_except_attrs_error
    Fiware-ServicePath: /test
payload: {"notification": {"http": {"url": "http://localhost:1234"}, "exceptAttrs": ["sxfcFzcH9jMod8iDNTyOfmSXug3X68Y6X4pfWyfCbC68G9n5EAARwwFI8gAa5YAS4QxSJtnL5aKVUEXxk7P60MlLxpXBhLSNui5egZYlEZ58ysZ0RBs3OH1rM1YuoyJRlWxgz5ZlBgqhTTGZ3eNBrgGxkoHZASlAadmRwAGOmteOKwE7ArVdy7GAxFmXXT836WE3D0kYzPJqOf00PN4aGY4ysZqPfQPU6itEB5YLqNRkEbbZH4S507SjQzVAG5gFg"]}, "expires": "2016-04-05T14:00:00.00Z", "subject": {"entities": [{"idPattern": ".*"}], "condition": {"attrs": ["temperature"]}}}
````
#### Response 
```
http code: 201 - Created
headers:
   date: Wed, 15 Jun 2016 15:44:16 GMT
   fiware-correlator: 04739892-3310-11e6-ae3c-005056a20feb
   connection: Keep-Alive
   content-length: 0
   location: /v2/subscriptions/576177d019a5cf2a59c7e037
payload:

```
