### ISSUE TITLE
Requests are accepted if we use Content-Type without payload or empty

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2128]
Requests are accept if we use Content-Type without payload or empty

Example

#### request:
```
url: DELETE http://qa-orion-fe-02:1026/v2/entities/room_1
headers:
    Content-Type: application/json
    Fiware-Service: test_delete_happy_path
    Fiware-ServicePath: /test
payload:
```

#### response:
```
http code: 204 - No Content
headers:
   date: Fri, 06 May 2016 11:16:48 GMT
   fiware-correlator: 0640acea-137c-11e6-8419-005056a20feb
   connection: Keep-Alive
   content-length: 0
payload:
```

#### expected:
```
http code: 400 -Bad Request
payload: {"error":"BadRequest","description":"empty payload"}
```
