### ISSUE TITLE
Virtual attributes dateCreation and dateModification not rendered

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-orion#2167]
When sending:

DEBUG >>>>>>>>>>>>>	 Data sent:     	>>>>>>>>>>>>> 
	> Comp: CB
	> Url: http://192.168.21.64:1026/v2/entities
	> Method: get
	> Headers: {'fiware-service': 'eeee', 'fiware-servicepath': '/uuu', 'Accept': 'application/json'}
	> Params sent: {'options': 'dateModification'}

CB responds:

DEBUG <<<<<<<<<<<<<<	 Data responded:	<<<<<<<<<<<<<<
	< Response code: 400
	< Headers: {'content-length': '76', 'server': 'nginx', 'fiware-correlator': 'c9d5fd18-1e8a-11e6-8b6c-fa163e026cb4', 'connection': 'keep-alive', 'date': 'Fri, 20 May 2016 13:00:12 GMT', 'content-type': 'application/json'}
	< Payload received:
 {"error":"BadRequest","description":"Invalid value for URI param /options/"}

version:

{
  "orion" : {
  "version" : "1.1.0_20160520020628",
  "uptime" : "0 d, 0 h, 2 m, 31 s",
  "git_hash" : "c96ceaf0437c989a21c388c5015fe4059f3bccff",
  "compile_time" : "Fri May 20 02:08:44 CEST 2016",
  "compiled_by" : "develenv",
  "compiled_in" : "ci-iot-deven-01"
}
}

**Comment by manucarrace** [comment]
Besides, it is not possible to use them in regexp with q parameter.

**Comment by fgalan** [comment]
It seem there is a missmatch beteen documentation

>    dateCreation (type: date): entity creation date as ISO 8601 string.
>    dateModification (type: date): entity modification date as ISO 8601 string.

and code:

```
#define DATE_CREATED   "dateCreated"
#define DATE_MODIFIED  "dateModified"
```

This is very easy to fix (either in doc or code) but first we should decide the right one. Taking into account that this is inspired in https://schema.org/DateTime, it seems that the code is correct and documentation isn't.

**Comment by fgalan** [comment]
Documentation fixed in PR commit https://github.com/telefonicaid/fiware-orion/pull/2161/commits/d03fbfcfb456598d3cb06bcd16302de9916fb770, part of PR #2161

**Comment by iariasleon** [comment]
Wth two entities created previously.

options values: **dateCreated** or **dateModified**

#### get request
```
url: GET http://192.168.21.64:10026/v2/entities?options=dateModified
headers:
    Fiware-Service: qap1
    Fiware-ServicePath: /ssp1
```
#### get response
```
http code: 200 - OK
headers:
   content-length: 422
   server: nginx
   fiware-correlator: e9fc3fb0-27f6-11e6-9dd4-fa163e026cb4
   connection: keep-alive
   date: Wed, 01 Jun 2016 12:46:52 GMT
   x-frame-options: SAMEORIGIN
   content-type: application/json
payload: [{"id":"room2","type":"house","temeperature":{"type":"celsius","value":34,"metadata":{"very_hot":{"type":"alarm","value":"hot"}}},"dateModified":{"type":"DateTime","value":"2016-06-01T12:46:51.00Z","metadata":{}}},{"id":"room3","type":"house","pressure":{"type":"bar","value":989,"metadata":{"very_hard":{"type":"alarm","value":"high"}}},"dateModified":{"type":"DateTime","value":"2016-06-01T12:46:52.00Z","metadata":{}}}]
```
