### ISSUE TITLE
in GET v2/entities/ using attrs parameter with unknown value

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2245]
in GET v2/entities/ using attrs parameter with unknown value, responds a 200 OK with payload without attributes instead of  an error message:

With 3 attributes created previously.

#### GET request:
```
url: GET http://qa-orion-fe-02:1026/v2/entities?attrs=fdgdfgdf
headers:
    Content-Type: application/json
    Fiware-Service: test_list_only_options
    Fiware-ServicePath: /test
```

#### GET response
```
http code: 200 - OK
headers:
   date: Tue, 07 Jun 2016 08:44:02 GMT
   fiware-correlator: fc21acfe-2c8b-11e6-91de-005056a20feb
   connection: Keep-Alive
   content-type: application/json
   content-length: 97
payload: [{"id":"room1_0","type":"home",},{"id":"room1_1","type":"home",},{"id":"room1_2","type":"home",}]
```

#### expected response
```
404 - Not Found
{"error":"NotFound","description":"Entities do not have such attribute"}
