### ISSUE TITLE
in POST v2/subscriptions if httpCustom url is empty the subcription is created

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2279]
in POST v2/subscriptions if notification **httpCustom** url is empty the subcription is created
#### subscription request

```
POST http://qa-orion-fe-02:1026/v2/subscriptions
headers:
    Content-Type: application/json
    Fiware-Service: test_notif_http_custom_url_error
    Fiware-ServicePath: /test
payload: {"notification": {"httpCustom": {"url": ""}, "attrs": ["temperature"]}, "expires": "2016-04-05T14:00:00.00Z", "subject": {"entities": [{"idPattern": ".*"}], "condition": {"attrs": ["temperature"]}}}
```
#### subcription response

```
http code: 201 - Created
headers:
   date: Wed, 15 Jun 2016 11:14:09 GMT
   fiware-correlator: 47e3b3d0-32ea-11e6-be09-005056a20feb
   connection: Keep-Alive
   content-length: 0
   location: /v2/subscriptions/57613940451e58b1a26c24b2
```
#### mongo doc

```
{ "_id" : ObjectId("57613940451e58b1a26c24b2"), "expiration" : NumberLong(1459864800), "reference" : "", "custom" : true, "throttling" : NumberLong(0), "servicePath" : "/test", "status" : "active", "entities" : [ { "id" : ".*", "isPattern" : "true" } ], "attrs" : [ "temperature" ], "blacklist" : false, "conditions" : [ { "type" : "ONCHANGE", "value" : [ "temperature" ] } ], "expression" : { "q" : "", "geometry" : "", "coords" : "", "georel" : "" }, "format" : "normalized" }
```
#### expected response

```
http code: 400 - Bad Request
payload: {"error":"BadRequest","description":"Invalid URL parsing notification url"}

```
