### ISSUE TITLE
Requests (DELETE, GET) are accepted if we use Content-Type with empty value

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2364]
Requests (DELETE, GET) are accepted if we use Content-Type with empty value. Issue related #2128.
#### request

```
url: DELETE http://localhost:1026/v2/entities/room_1
headers:
    Content-Type:
    Fiware-Service: test_delete_happy_path
    Fiware-ServicePath: /test
```
#### Response

```
http code: 204 - No Content
headers:
   date: Fri, 15 Jul 2016 10:15:39 GMT
   fiware-correlator: 1442db30-4a75-11e6-9c10-005056a20feb
   connection: Keep-Alive
   content-length: 0
payload:
```
#### expected

```
http code: 400
{
   "error":"BadRequest",
   "description":"Orion accepts no payload for GET/DELETE requests. HTTP header Content-Type is thus forbidden"
}
```
#### log message

```
time=2016-07-15T10:50:43.637Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=httpHeaderGet | comp=Orion | msg=rest.cpp[486]: HTTP Header:   Content-Type:

```
