### ISSUE TITLE
in PUT /v2/entities/<id>/attrs/<attr_name>/value if missing citation-mark returns an error in NGSI v1 format

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2386]
in PUT `/v2/entities/<id>/attrs/<attr_name>/value` if missing citation-mark returns an error in NGSI v1 format

#### Request
```
url: PUT http://qa-orion-fe-02:1026/v2/entities/room/attrs/temperature/value
headers:
    Content-Type: text/plain
    Fiware-Service: test_update_attribute_value_special
    Fiware-ServicePath: /test
payload: "rwerwer
```
####  Response 
```
http code: 200 - OK
headers:
   date: Wed, 27 Jul 2016 09:12:55 GMT
   fiware-correlator: 4defdeaa-53da-11e6-93f9-005056a20feb
   connection: Keep-Alive
   content-type: application/json
   content-length: 140
payload: {
  "orionError" : {
    "code" : "400",
    "reasonPhrase" : "Bad Request",
    "details" : "Missing citation-mark at end of string"
  }
}
```

#### Expected
```
http code: 400 - Bad Request
payload: {"error":"BadRequest","description":"Missing citation-mark at end of string"}
```

**Comment by kzangeli** [comment]
Probably, this error in the payload is discovered before the URL is looked at to decide if we are in NGSIv1 or NGSIv2 mode, and the error response is done in NGSIv1

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/2416

**Comment by fgalan** [comment]
Please @iariasleon have a look and close it if you find it fixed.

**Comment by iariasleon** [comment]
LGTM
```
`http code: 400 - Bad Request
headers:
   date: Wed, 03 Aug 2016 08:03:44 GMT
   fiware-correlator: cc59da7c-5950-11e6-835e-005056a20feb
   connection: Keep-Alive
   content-type: application/json
   content-length: 77
payload: {"error":"BadRequest","description":"Missing citation-mark at end of string"}
```
