### ISSUE TITLE
in  PATCH /v2/entities/<id>/attrs using "." in metaName, it is duplicate in mdNames into mongoDB 

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2394]
in  PATCH `/v2/entities/<id>/attrs` using "." in metaName, it is duplicate in **mdNames** into mongoDB 

#### mongo doc before the update
```
{ "_id" : { "id" : "room_1", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "celsius", "creDate" : 1469699345, "modDate" : 1469699345, "value" : "345", "md" : { "34=4E-34_1" : { "type" : "alarm", "value" : "hot" }, "34=4E-34_0" : { "type" : "alarm", "value" : "hot" } }, "mdNames" : [ "34.4E-34_1", "34.4E-34_0" ] } }, "creDate" : 1469699345, "modDate" : 1469699345 }
```

#### update request
```
url: PATCH http://localhost:1026/v2/entities/room_1/attrs
headers:
    Content-Type: application/json
    Fiware-Service: test_attribute_metadata_name_update
    Fiware-ServicePath: /test
payload: {"temperature": {"value": "106", "metadata": {"34.4E-34_1": {"value": "5678"}, "34.4E-34_0": {"value": "5678"}}}}

```

#### mongo doc after the update 
```
{ "_id" : { "id" : "room_1", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "value" : "106", "type" : "none", "md" : { "34=4E-34_1" : { "type" : "none", "value" : "5678" }, "34=4E-34_0" : { "type" : "none", "value" : "5678" } }, "mdNames" : [ "34.4E-34_1", "34.4E-34_0", "34=4E-34_0", "34=4E-34_1" ], "creDate" : 1469699345, "modDate" : 1469699345 } }, "creDate" : 1469699345, "modDate" : 1469699345 }
```

See `mdNames` field: 
```
"mdNames" : [ "34.4E-34_1", "34.4E-34_0", "34=4E-34_0", "34=4E-34_1" ]
```
