### ISSUE TITLE
in GET v2/entities if are using "mq" query param, the date are not processed

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2443]
in GET v2/entities if are using "mq" query param, the date are not processed. The "DateTime" type is defined in the metadata.

#### dataset
```
      | mq_expression                                                              |
      |----------------------------------------------------------------------------|
      | timestamp.meta_timestamp==2017-06-15T07:21:24.00Z                          | 
      | timestamp.meta_timestamp>=2017-06-15T07:21:24.00Z                          | 
      | timestamp.meta_timestamp>=2016-06-15T07:21:24.00Z                          | 
      | timestamp.meta_timestamp>2016-06-15T07:21:24.00Z                           | 
      | timestamp.meta_timestamp<=2017-06-15T07:21:24.00Z                          | 
      | timestamp.meta_timestamp<=2026-06-15T07:21:24.00Z                          | 
      | timestamp.meta_timestamp<2026-06-15T07:21:24.00Z                           | 
      | timestamp.meta_timestamp==2016-06-15T07:21:24.00Z..2026-06-15T07:21:24.00Z |
```

#### entity request
```
url: POST http://localhost:1026/v2/entities
headers:
    Content-Type: application/json
    Fiware-Service: s01801pep2cbv2
    Fiware-ServicePath: /ssp1
payload: {"type": "hy6K", "id": "room4",  "temperature":{"type": "celsius", "metadata": {"meta_temperature": {"value": 34, "type": "alarm"}}, "value": 34}, "pressure":{"metadata": {"meta_pressure": {"value": "high"}}, "value": 35}, "humidity":{"type": "porcent", "metadata": {"meta_humidity": {"value": "air,density"}}, "value": 36}, "timestamp":{"type": "nothing", "metadata": {"meta_timestamp": {"value": "2017-06-15T07:21:24.00Z", "type": "DateTime"}}, "value": 37}, "value_str":{"metadata": {"meta_value_str": {"value": "true"}}, "value": 38}, "value_bool":{"metadata": {"meta_value_bool": {"value": true, "type": "alarm"}}, "value": 39}}
```

#### GET request with "mq" query parameter
```
url: GET http://localhost:1026/v2/entities?mq=timestamp.meta_timestamp>=2017-06-15T07:21:24.00Z&options=count
headers:
    Fiware-Service: s01801pep2cbv2
    Fiware-ServicePath: /ssp1
```

#### GET response
```
http code: 200 - OK
headers:
   content-length: 2
   fiware-total-count: 0
   server: nginx
   fiware-correlator: 7361c1fa-5f9a-11e6-aaa6-fa163e026cb4
   connection: keep-alive
   date: Thu, 11 Aug 2016 08:06:04 GMT
   content-type: application/json
payload: []
```
