### ISSUE TITLE
in POST v2/subscriptions, if we use  "mq" query param to validate a "DateTime" some operators do not notify

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2445]
in POST v2/subscriptions, if we use  "mq" query param to validate a "DateTime" some operators do not notify (`==`, `<` and `>`). Anothers operators (`>=`, `<=` and `!=`) notify correctly.

#### dataset
```
      | mq_expression                                                              |
      |----------------------------------------------------------------------------|
      | timestamp.meta_timestamp==2017-06-15T07:21:24.00Z                          |
      | timestamp.meta_timestamp>2016-06-15T07:21:24.00Z                           |
      | timestamp.meta_timestamp<2026-06-15T07:21:24.00Z                           |
      | timestamp.meta_timestamp==2016-06-15T07:21:24.00Z..2026-06-15T07:21:24.00Z |
```

#### subscription request
```
url: POST http://localhost1026/v2/subscriptions
headers:
    Content-Type: application/json
    Fiware-Service: s01801pep2cbv2
    Fiware-ServicePath: /ssp1
payload: { "subject": {"entities": [{"idPattern": ".*"}], "condition": { "attrs": ["temperature"], "expression": {  "mq": "timestamp.meta_timestamp==2016-06-15T07:21:24.00Z..2026-06-15T07:21:24.00Z"} }}, "notification": {"http": { "url": "http://localhost:10032/notify"}, "attrs": ["temperature","pressure","humidity","timestamp","value_str","value_bool"]} }
```

#### entity request
```
url: POST http://localhost:10026/v2/entities
headers:
    Content-Type: application/json
    Fiware-Service: s01801pep2cbv2
    Fiware-ServicePath: /ssp1
payload: {"type": "Ph9h", "id": "room4",  "temperature":{"type": "celsius", "metadata": {"meta_temperature": {"value": 34, "type": "alarm"}}, "value": 34}, "pressure":{"metadata": {"meta_pressure": {"value": "high"}}, "value": 35}, "humidity":{"type": "porcent", "metadata": {"meta_humidity": {"value": "air,density"}}, "value": 36}, "timestamp":{"type": "nothing", "metadata": {"meta_timestamp": {"value": "2017-06-15T07:21:24.00Z", "type": "DateTime"}}, "value": 37}, "value_str":{"metadata": {"meta_value_str": {"value": "true"}}, "value": 38}, "value_bool":{"metadata": {"meta_value_bool": {"value": true, "type": "alarm"}}, "value": 39}}
```
