### ISSUE TITLE
in GET v2/entities with the "mq" query param fails randomly if we use a vector in "metadata values" 

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2446]
in GET v2/entities with the "mq" query param fails **randomly**  if we use a vector in "metadata values". In execution of tests in group, if the test is executed alone never fails. The problem is probably in the stack.

#### Entity request
```
url: POST http://localhost:1026/v2/entities
headers:
    Content-Type: application/json
    Fiware-Service: s01901pep2cbv2
    Fiware-ServicePath: /ssp1
payload: {"type": "t96C", "id": "room1",  "temperature":{"type": "celsius", "metadata": {"very_cold": {"value": ["one","two","three"], "type": "alarm"}}, "value": 45}}
```

#### GET request
```
url: GET http://localhost:1026/v2/entities?mq=temperature.very_cold==one&options=count
headers:
    Fiware-Service: s01901pep2cbv2
    Fiware-ServicePath: /ssp1
```

#### GET response
```
`http code: 200 - OK
headers:
   content-length: 136
   fiware-total-count: 1
   server: nginx
   fiware-correlator: f2b421ba-5fad-11e6-b8d3-fa163e026cb4
   connection: keep-alive
   date: Thu, 11 Aug 2016 10:25:38 GMT
   content-type: application/json
payload: [{"id":"room1","type":"t96C","temperature":{"type":"celsius","value":45,"metadata":{"very_cold":{"type":"alarm","one","two","three"}}}}]
```

#### expected response
```
http code: 200 - OK
payload: [{"id":"room1","type":"nQIa","temperature":{"type":"celsius","value":45,"metadata":{"very_cold":{"type":"alarm","value":["one","two","three"]}}}}]
```
