### ISSUE TITLE
Patterns with backlash are not procceded correctly when they are used in URL param that use regex

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2490]
Patterns with backlash are not procceded correctly when they are used in URL param that use regex
Examples:
```
\S   \D  \s  \w 
```
We have 4 entities previously.

#### GET entities list
**\d** could mean any digit
```
GET http://localhost:1026/v2/entities?idPattern=\d*&options=count
GET http://localhost:1026/v2/entities?typePattern=\d*&options=count
```

#### Response
```
http code: 200 - OK
headers:
   ....
   fiware-total-count: 4  
payload: [
    {"id":"random","type":"FF4S","temperature":{"type":"Number","value":24,"metadata":{}}},
    {"id":"car","type":"vehicle","temperature":{"type":"Number","value":34,"metadata":{}}},
    {"id":"nothing","type":"tetetete","temperature":{"type":"Number","value":44,"metadata":{}}},
    {"id":"12345678","type":"12345678","temperature":{"type":"Number","value":54,"metadata":{}}}]
```

#### Response expected
```
http code: 200 - OK
headers:
   ....
   fiware-total-count: 1  
payload: [   
    {"id":"12345678","type":"12345678","temperature":{"type":"Number","value":54,"metadata":{}}}]
```

**Comment by fgalan** [comment]
Note that

A .test has been developed to cover the case in PR https://github.com/telefonicaid/fiware-orion/pull/2504

**Comment by iariasleon** [comment]
LGTM
```
url: POST http://localhost:1026/v2/op/query?options=keyValues,count
headers:
    Content-Type: application/json
    Fiware-Service: s02001pep2cbv2
    Fiware-ServicePath: /ssp1
payload: {"entities": [{"idPattern": ".*", "typePattern": "\\d+"}], "attributes": ["temperature"]}
 ----------------- Response ---------------------------------
http code: 200 - OK
headers:
   Server: nginx
   Date: Mon, 12 Sep 2016 08:51:38 GMT
   Content-Type: application/json
   Content-Length: 55
   Connection: keep-alive
   fiware-correlator: 1de825f8-78c6-11e6-aec9-fa163e026cb4
   fiware-total-count: 1
payload: [{"id":"numeric","type":"12345678","temperature":"54"}]

```
