### ISSUE TITLE
in POST v2/op/query using typePattern with backslash are not processed correctly 

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2494]
in POST **v2/op/query**  using typePattern with backslash are not processed correctly, returning all entities.
Examples:
```
\S \d  \D  \s  \w 
```
We have 4 entities previously.

#### Query batch op request
```
POST http://192.168.21.64:10026/v2/op/query?options=keyValues,count
headers:
    Content-Type: application/json
payload: {"entities": [{"idPattern": ".*", "typePattern": "\\d*"}], "attributes": ["temperature"]}
```
#### Query response
```
http code: 200 - OK
headers:
   ...
   fiware-total-count: 4
payload: [{"id":"room1","type":"house","temperature":"24"},{"id":"car","type":"vehicle","temperature":"34"},{"id":"nothing","type":"tetetete","temperature":"44"},{"id":"numeric","type":"12345678","temperature":"54"}]
```

#### Expexted query response
```
http code: 200 - OK
headers:
   ...
   fiware-total-count: 1
payload: [{"id":"numeric","type":"12345678","temperature":"54"}]
```

Similar Issue: #2490

**Comment by fgalan** [comment]
Note that `\d*` will match "0 or more digits". Thus, probably you should use `\d+` for "1 or more digits".

(Actually, `\\d+`, as in JSON payloads `\` is encoded by `\\`).

A .test has been developed to cover the case in PR https://github.com/telefonicaid/fiware-orion/pull/2504

**Comment by iariasleon** [comment]
LGTM
```
url: POST http://localhost:1026/v2/op/query?options=keyValues,count
headers:
    Content-Type: application/json
    Fiware-Service: s02001pep2cbv2
    Fiware-ServicePath: /ssp1
payload: {"entities": [{"idPattern": ".*", "typePattern": "\\d+"}], "attributes": ["temperature"]}
 ----------------- Response ---------------------------------
http code: 200 - OK
headers:
   Server: nginx
   Date: Mon, 12 Sep 2016 08:51:38 GMT
   Content-Type: application/json
   Content-Length: 55
   Connection: keep-alive
   fiware-correlator: 1de825f8-78c6-11e6-aec9-fa163e026cb4
   fiware-total-count: 1
payload: [{"id":"numeric","type":"12345678","temperature":"54"}]

```
