### ISSUE TITLE
The "type" in "previousValue" notification metadata is wrong if we use /v2/entities/<id>/attrs/<name>/value

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2553]
The "type" in "previousValue" notification metadata is wrong if we use `/v2/entities/<id>/attrs/<name>/value`

In this request is only updated the value correctly, see mongo doc, but the `previousValue` returns a type by default.

#### mongo doc
```
`{ "_id" : { "id" : "room2", "type" : "y2a", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "value" : "h5Gff0Ku", "type" : "celsius", "md" : { "very_hot_0" : { "type" : "alarm", "value" : "hot" }, "very_hot_1" : { "type" : "alarm", "value" : "hot" } }, "mdNames" : [ "very_hot_0", "very_hot_1" ], "creDate" : 1475147728, "modDate" : 1475147729 } }, "creDate" : 1475147728, "modDate" : 1475147729 }
```

#### subscription create request
```
url: POST http://localhost:1026/v2/subscriptions
headers:
    Content-Type: application/json
    Fiware-Service: test_notif_metadata_update_put
    Fiware-ServicePath: /test
payload: {"notification": {"http": {"url": "http://localhost:1045/notify"}, "metadata": ["previousValue"]}, "subject": {"entities": [{"idPattern": ".*"}]}}
```

#### entity create request
```
url: POST http://localhost:1026/v2/entities
headers:
    Content-Type: application/json
    Fiware-Service: test_notif_metadata_update_put
    Fiware-ServicePath: /test
payload: {"type": "y2a", "temperature": {"type": "celsius", "value": "00eqv", "metadata": {"very_hot_1": {"type": "alarm", "value": "hot"}, "very_hot_0": {"type": "alarm", "value": "hot"}}}, "id": "room2"}
```

#### attribute value update request
```
url: PUT http://qa-orion-fe-02:1026/v2/entities/room2/attrs/temperature/value
headers:
    Content-Type: text/plain
    Fiware-Service: test_notif_metadata_update_put
    Fiware-ServicePath: /test
payload: "h5Gff0Ku"
```

#### notification sent
```
 {"subscriptionId":"57ecf7d004a723793ba2dc34","data":[{"id":"room2","type":"y2a","temperature":{"type":"celsius","value":"h5Gff0Ku","metadata":{"previousValue":{"type":"Text","value":"00eqv"}}}}]}
```

#### notification expected
```
 {"subscriptionId":"57ecf7d004a723793ba2dc34","data":[{"id":"room2","type":"y2a","temperature":{"type":"celsius","value":"h5Gff0Ku","metadata":{"previousValue":{"type":"celsius","value":"00eqv"}}}}]}
```
