### ISSUE TITLE
in POST v2/op/update, if we use an unknown action the op is successful

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2653]
in POST v2/op/update, if we use an unknown action `"actionType": "dfgdf"` the op is successfully

#### update bach operation request
```
POST localhost:1026/v2/op/update
headers:
    Content-Type: application/json
    Fiware-Service: test_op_update_happy_path
    Fiware-ServicePath: /test
payload: {"entities": [{"type": "house", "temperature": {"value": "34"}, "id": "room1_0"}, {"type": "house", "temperature": {"value": "34"}, "id": "room1_1"}, {"type": "house", "temperature": {"value": "34"}, "id": "room1_2"}, {"type": "house", "temperature": {"value": "34"}, "id": "room1_3"}, {"type": "house", "temperature": {"value": "34"}, "id": "room1_4"}], "actionType": "dfgdf"}
```

#### update bach operation response
```
http code: 204 - No Content
headers:
   Connection: Keep-Alive
   Content-Length: 0
   Fiware-Correlator: 84769862-a766-11e6-98a0-005056a20feb
   Date: Thu, 10 Nov 2016 16:55:43 GMT
payload:
```

#### docs in mongo
```
{ "_id" : { "id" : "room1_0", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1478797236, "modDate" : 1478797236, "value" : "34", "mdNames" : [ ] } }, "creDate" : 1478797236, "modDate" : 1478797236 }
{ "_id" : { "id" : "room1_1", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1478797236, "modDate" : 1478797236, "value" : "34", "mdNames" : [ ] } }, "creDate" : 1478797236, "modDate" : 1478797236 }
{ "_id" : { "id" : "room1_2", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1478797236, "modDate" : 1478797236, "value" : "34", "mdNames" : [ ] } }, "creDate" : 1478797236, "modDate" : 1478797236 }
{ "_id" : { "id" : "room1_3", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1478797236, "modDate" : 1478797236, "value" : "34", "mdNames" : [ ] } }, "creDate" : 1478797236, "modDate" : 1478797236 }
{ "_id" : { "id" : "room1_4", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1478797236, "modDate" : 1478797236, "value" : "34", "mdNames" : [ ] } }, "creDate" : 1478797236, "modDate" : 1478797236 }

```
