### ISSUE TITLE
in POST v2/op/update (batch op) not plain ascii chars are allowed in entities.id

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2658]
in POST v2/op/update (batch op) not plain ascii chars are allowed in entities.id.See similar issue: #2664.

#### Dataset used
```
      | entities_id |
      |-------------|
      | habitación  |
      | españa      |
      | barça       |
```
#### update batch operation request
```
url: POST http://localhost:1026/v2/op/update
headers:
    Content-Type: application/json
    Fiware-Service: test_op_update_entitiies_id_error
    Fiware-ServicePath: /test
payload: {"entities": [{"type": "house", "temperature": {"type": "celsius", "value": "4", "metadata": {"alarm": {"type": "hot", "value": "warning"}}}, "id": "barça"}], "actionType": "APPEND"}
```

#### Response
```
http code: 204 - No Content
headers:
   Connection: Keep-Alive
   Content-Length: 0
   Fiware-Correlator: d783381e-a818-11e6-a306-005056a20feb
   Date: Fri, 11 Nov 2016 14:12:13 GMT
payload:
```

#### Expected response
```
http code: 400 - Bad Request
{"error":"BadRequest","description":"Invalid characters in entity id"}

```

#### doc in mongo
```
`{ "_id" : { "id" : "habitación", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "celsius", "creDate" : 1478873863, "modDate" : 1478873863, "value" : "4", "md" : { "alarm" : { "type" : "hot", "value" : "warning" } }, "mdNames" : [ "alarm" ] } }, "creDate" : 1478873863, "modDate" : 1478873863 }
{ "_id" : { "id" : "españa", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "celsius", "creDate" : 1478873863, "modDate" : 1478873863, "value" : "4", "md" : { "alarm" : { "type" : "hot", "value" : "warning" } }, "mdNames" : [ "alarm" ] } }, "creDate" : 1478873863, "modDate" : 1478873863 }
{ "_id" : { "id" : "barça", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "celsius", "creDate" : 1478873863, "modDate" : 1478873863, "value" : "4", "md" : { "alarm" : { "type" : "hot", "value" : "warning" } }, "mdNames" : [ "alarm" ] } }, "creDate" : 1478873863, "modDate" : 1478873863 }
```
```
