### ISSUE TITLE
in POST v2/op/update (batch op) not plain ascii chars are allowed in entitites.type

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2664]
in POST v2/op/update (batch op) not plain ascii chars are allowed in entitites.type. See similar issue: #2658.

#### Dataset used
```
      | entities_id |
      |-------------|
      | habitación  |
      | españa      |
      | barça       |
```
#### update batch operation request
```
url: POST http://localhost:1026/v2/op/update
headers:
    Content-Type: application/json
    Fiware-Service: test_op_update_entitiies_type_error
    Fiware-ServicePath: /test
payload: {"entities": [{"type": "barça", "temperature": {"type": "celsius", "value": "4", "metadata": {"alarm": {"type": "hot", "value": "warning"}}}, "id": "room_2"}], "actionType": "APPEND"}
```

#### Response
```
http code: 204 - No Content
headers:
   Connection: Keep-Alive
   Content-Length: 0
   Fiware-Correlator: 8bc03ac0-aa53-11e6-86e7-005056a20feb
   Date: Mon, 14 Nov 2016 10:17:28 GMT
payload:
```

#### Expected response
```
http code: 400 - Bad Request
{"error":"BadRequest","description":"Invalid characters in entity type"}
```

#### doc in mongo
```
{ "_id" : { "id" : "room_2", "type" : "habitación", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "celsius", "creDate" : 1479119813, "modDate" : 1479119813, "value" : "4", "md" : { "alarm" : { "type" : "hot", "value" : "warning" } }, "mdNames" : [ "alarm" ] } }, "creDate" : 1479119813, "modDate" : 1479119813 }
{ "_id" : { "id" : "room_2", "type" : "españa", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "celsius", "creDate" : 1479119813, "modDate" : 1479119813, "value" : "4", "md" : { "alarm" : { "type" : "hot", "value" : "warning" } }, "mdNames" : [ "alarm" ] } }, "creDate" : 1479119813, "modDate" : 1479119813 }
{ "_id" : { "id" : "room_2", "type" : "barça", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "celsius", "creDate" : 1479119813, "modDate" : 1479119813, "value" : "4", "md" : { "alarm" : { "type" : "hot", "value" : "warning" } }, "mdNames" : [ "alarm" ] } }, "creDate" : 1479119813, "modDate" : 1479119813 }
```
