### ISSUE TITLE
in POST v2/op/update (batch op) validations fail for attr_value

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2681]
#### dataset used
```
      | attributes_value |
      |------------------|
      | house<flat>      |
      | house=flat       |
      | house"flat"      |
      | house'flat'      |
      | house;flat       |
      | house(flat)      |
```

#### update batch op request
```
url: POST http://localhost:1026/v2/op/update
headers:
    Content-Type: application/json
    Fiware-Service: test_op_update_attribute_value
    Fiware-ServicePath: /test
payload: {"entities": [{"type": "house", "temperature": {"value": "house(flat)", "metadata": {"warning": {"type": "alarm", "value": "hot"}}}, "id": "Wes"}], "actionType": "APPEND"}
```

#### update batch op response
```
http code: 204 - No Content
headers:
   Connection: Keep-Alive
   Content-Length: 0
   Fiware-Correlator: a222e0b8-abef-11e6-a733-005056a20feb
   Date: Wed, 16 Nov 2016 11:27:18 GMT
payload:
```

#### Expected response
```
http code: 400 - Bad Request
{"error":"BadRequest","description":"Invalid characters in attribute value"}
```

#### mongo docs
```
{ "_id" : { "id" : "1A6", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1479295856, "modDate" : 1479295856, "value" : "house<flat>", "md" : { "warning" : { "type" : "alarm", "value" : "hot" } }, "mdNames" : [ "warning" ] } }, "creDate" : 1479295856, "modDate" : 1479295856 }
{ "_id" : { "id" : "jDV", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1479295856, "modDate" : 1479295856, "value" : "house=flat", "md" : { "warning" : { "type" : "alarm", "value" : "hot" } }, "mdNames" : [ "warning" ] } }, "creDate" : 1479295856, "modDate" : 1479295856 }
{ "_id" : { "id" : "i3f", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1479295857, "modDate" : 1479295857, "value" : "house\"flat\"", "md" : { "warning" : { "type" : "alarm", "value" : "hot" } }, "mdNames" : [ "warning" ] } }, "creDate" : 1479295857, "modDate" : 1479295857 }
{ "_id" : { "id" : "eyL", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1479295857, "modDate" : 1479295857, "value" : "house'flat'", "md" : { "warning" : { "type" : "alarm", "value" : "hot" } }, "mdNames" : [ "warning" ] } }, "creDate" : 1479295857, "modDate" : 1479295857 }
{ "_id" : { "id" : "AsQ", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1479295857, "modDate" : 1479295857, "value" : "house;flat", "md" : { "warning" : { "type" : "alarm", "value" : "hot" } }, "mdNames" : [ "warning" ] } }, "creDate" : 1479295857, "modDate" : 1479295857 }
{ "_id" : { "id" : "Wes", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "type" : "Text", "creDate" : 1479295857, "modDate" : 1479295857, "value" : "house(flat)", "md" : { "warning" : { "type" : "alarm", "value" : "hot" } }, "mdNames" : [ "warning" ] } }, "creDate" : 1479295857, "modDate" : 1479295857 }

```
