### ISSUE TITLE
in POST v2/op/update (batch op) if we do not use entity type (optional) it is assumed as empty

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2685]
in POST v2/op/update (batch op) if we do not use entity type (optional) it is assumed as empty. It is related to #2665.

#### update batch op request
```
url: POST http://localhost:1026/v2/op/update
headers:
    Content-Type: application/json
    Fiware-Service: test_op_update_entities_type_error
    Fiware-ServicePath: /test
payload: {"entities": [{"temperature": {"type": "celsius", "value": "4", "metadata": {"alarm": {"type": "hot", "value": "warning"}}}, "id": "room_4"}], "actionType": "APPEND"}
```

#### update response
```
http code: 400 - Bad Request
headers:
   Connection: Keep-Alive
   Content-Length: 85
   Content-Type: application/json
   Fiware-Correlator: 443fdb4a-ac1c-11e6-9947-005056a20feb
   Date: Wed, 16 Nov 2016 16:46:48 GMT
payload: {"error":"BadRequest","description":"entity type length: 0, min length supported: 1"}
```

#### expected response
```
http code: 204 - No Content
```
