### ISSUE TITLE
in POST v2/subscriptions the notification.http.url field does not accept ipv6 

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2859]
in POST v2/subscriptions the notification.http.url field does not accept ipv6 

#### dataset used
```
      | url                                                            |
      |----------------------------------------------------------------|
      | http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html |
      | http://[1080:0:0:0:8:800:200C:417A]/index.html                 |
      | http://[3ffe:2a00:100:7031::1]                                 |
      | http://[1080::8:800:200C:417A]/foo                             |
      | http://[::192.9.5.5]/ipng                                      |
      | http://[::FFFF:129.144.52.38]:80/index.html                    |
      | http://[2010:836B:4179::836B:4179]                             |
```

#### subscription request
```
url: POST http://localhost:1026/v2/subscriptions
headers:
    Content-Type: application/json
    Fiware-Service: test_notification_http_url
    Fiware-ServicePath: /test
payload: {"notification": {"http": {"url": "http://[2010:836B:4179::836B:4179]"}, "attrs": ["temperature"]}, "subject": {"entities": [{"idPattern": ".*"}], "condition": {"attrs": ["temperature"]}}}
```
###  Response
```
http code: 400 - Bad Request
headers:
   Connection: Keep-Alive
   Content-Length: 79
   Content-Type: application/json
   Fiware-Correlator: 60f059f6-e7bb-11e6-9998-005056a20feb
   Date: Tue, 31 Jan 2017 13:44:25 GMT
payload: {"error":"BadRequest","description":"Invalid URL parsing notification url""}
```

**Comment by iariasleon** [comment]
Also, in POST v2/subscriptions the notification.httpcustom.url field neither accepts the ipv6 address, using the same datased (See above).

#### subscription request
```
url: POST http://localhost:1026/v2/subscriptions
headers:
    Content-Type: application/json
    Fiware-Service: test_notification_http_custom_url
    Fiware-ServicePath: /test
payload: {"notification": {"httpCustom": {"url": "http://[2010:836B:4179::836B:4179]"}, "attrs": ["temperature"]}, "subject": {"entities": [{"idPattern": ".*"}], "condition": {"attrs": ["temperature"]}}}

```
###  Response
```
http code: 400 - Bad Request
headers:
   Connection: Keep-Alive
   Content-Length: 59
   Content-Type: application/json
   Fiware-Correlator: 4409dd84-e7cb-11e6-a237-005056a20feb
   Date: Tue, 31 Jan 2017 15:38:08 GMT
payload: {"error":"BadRequest","description":"invalid custom /url/"}

```
