### ISSUE TITLE
Error on StructuredValue attribute type when using commands on a IoT device

### ISSUE THREAD

**Issue by tioperez** [telefonicaid/fiware-orion#3363]
I've deployed the iot stack with docker. These are the used containers:

- fiware/orion:2.0.0
- fiware/iotagent-json:1.8.0

[other containers not involved in the issue ...]

**Documentation consulted:**
- [FIWARE-NGSI v2 Specification][1]
- [IoT Agent Provision API Documentation > Devices > Device Model > commands][2]

----------

**GIVEN:** A device ready to receive a command called "ping"

``` json
{
    "device_id": "sensor001",
    "entity_name": "sensor001",
    "entity_type": "TestType",
    "transport": "HTTP",
    "protocol": "IoTA-JSON",
    "endpoint": "http://simulator:3000/iot/test-type/sensor001",
    "commands": [
        {
            "name": "ping",
            "type": "command"
        }
    ],
    "attributes": [
        {
            "object_id": "status",
            "name": "status",
            "type": "Text"
        }
    ],
    "static_attributes": [
        {
            "name": "name",
            "type": "Text",
            "value": "Sensor 001"
        }
    ]
}
```

Creating that Device through the **IoT Agent JSON**

``` shell
curl --request POST \
  --url http://localhost:4041/iot/devices \
  --header 'Content-Type: application/json' \
  --header 'Fiware-Service: testService' \
  --header 'Fiware-ServicePath: /testPath' \
  --data '{"devices":[{"device_id":"sensor001","entity_name":"sensor001","entity_type":"TestType","transport":"HTTP","protocol":"IoTA-JSON","endpoint":"http://simulator:3000/iot/test-type/sensor001","commands":[{"name":"ping","type":"command"}],"attributes":[{"object_id":"status","name":"status","type":"Text"}],"static_attributes":[{"name":"name","type":"Text","value":"Sensor 001"}]}]}'
```

**WHEN**: Update or append to that entity now in Orion CB an attribute of type **StructuredValue**

``` shell
curl --request POST \
  --url http://localhost:1026/v2/entities/sensor001/attrs \
  --header 'Content-Type: application/json' \
  --header 'fiware-service: testService' \
  --header 'fiware-servicepath: /testPath' \
  --data '{"example_attr":{"type":"StructuredValue","value":{"exampleField":"exampleValue"}}}
```

**THEN**: Retrieve an entity by ID sensor001 or List entities

    curl --request GET \
      --url http://localhost:1026/v2/entities/sensor001 \
      --header 'fiware-service: testService' \
      --header 'fiware-servicepath: /testPath'

### The response does not contains the value for the attribute example_attr

``` shell
{
    "id": "sensor001",
    "type": "TestType",
    "TimeInstant": {
        "type": "ISO8601",
        "value": " ",
        "metadata": {}
    },
    "example_attr": {
        "type": "StructuredValue",
        "metadata": {}
    },
    "name": {
        "type": "Text",
        "value": "Sensor 001",
        "metadata": {}
    },
    "status": {
        "type": "Text",
        "value": " ",
        "metadata": {}
    }
}
```

## So the issue appears when you use commands array creating a device through the **IoT Agent JSON**

``` shell
"commands": [
        {
            "name": "ping",
            "type": "command"
        }
    ]
```

  [1]: http://fiware.github.io/specifications/ngsiv2/stable/
  [2]: https://telefonicaiotiotagents.docs.apiary.io/#reference/configuration-api/devices

**Comment by fgalan** [comment]
> So the issue appears when you use commands array creating a device through the IoT Agent JSON

You mean that if you do the provision of the devide using this 

```
  --data '{"devices":[{"device_id":"sensor001","entity_name":"sensor001","entity_type":"TestType","transport":"HTTP","protocol":"IoTA-JSON","endpoint":"http://simulator:3000/iot/test-type/sensor001","attributes":[{"object_id":"status","name":"status","type":"Text"}],"static_attributes":[{"name":"name","type":"Text","value":"Sensor 001"}]}]}'
```

Then it works as expected?

**Comment by tioperez** [comment]
> > So the issue appears when you use commands array creating a device through the IoT Agent JSON
> 
> You mean that if you do the provision of the device using this
> 
> ```
>   --data '{"devices":[{"device_id":"sensor001","entity_name":"sensor001","entity_type":"TestType","transport":"HTTP","protocol":"IoTA-JSON","endpoint":"http://simulator:3000/iot/test-type/sensor001","attributes":[{"object_id":"status","name":"status","type":"Text"}],"static_attributes":[{"name":"name","type":"Text","value":"Sensor 001"}]}]}'
> ```
> Then it works as expected?

Yes, If you don't add commands array to that object, then it work as expected.

**Comment by fgalan** [comment]
What about if you provision using the command array but you get the attribute individually, i.e.:

```
GET /v2/entities/sensor001/attrs/TimeInstant
GET /v2/entities/sensor001/attrs/example_attr
GET /v2/entities/sensor001/attrs/name
GET /v2/entities/sensor001/attrs/status
```

Is that working?

**Comment by tioperez** [comment]
> What about if you provision using the command array but you get the attribute individually, i.e.:
> 
> ```
> GET /v2/entities/sensor001/attrs/TimeInstant
> GET /v2/entities/sensor001/attrs/example_attr
> GET /v2/entities/sensor001/attrs/name
> GET /v2/entities/sensor001/attrs/status
> ```
> Is that working?

Isn't working, the behaviour is the same.

**Comment by fgalan** [comment]
I'll try to reproduce the problem. Could you post the docker-compose.yml you are using (reduced to the relevant container) so I can replay your same test, please?

**Comment by tioperez** [comment]
> I'll try to reproduce the problem. Could you post the docker-compose.yml you are using (reduced to the relevant container) so I can replay your same test, please?

Thanks @fgalan here you are.

``` yml
version: "3.7"
services:
  orion:
    image: fiware/orion:2.0.0
    container_name: orion
    restart: always
    depends_on:
      - mongo-orion
    ports:
      - "1026:1026"
    command: -corsOrigin __ALL -corsMaxAge 600 -dbhost mongo-orion

  iotagent-json:
    image: fiware/iotagent-json:1.8.0
    container_name: iotagent-json
    restart: always
    depends_on:
      - mongo-orion
      - orion
    ports:
      - "4041:4041"
      - "7896:7896"
    environment:
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_LOG_LEVEL=DEBUG"
      - "IOTA_TIMESTAMP=true"
      - "IOTA_MONGO_HOST=mongo-orion"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagent-json"
      - "IOTA_HTTP_PORT=7896"
      - "IOTA_PROVIDER_URL=http://iotagent-json:4041"

  mongo-orion:
    image: mongo:3.4
    container_name: mongo-orion
    restart: always
    ports:
      - "27017:27017"
```

**Comment by fgalan** [comment]
For the records, an equivalente version of docker-compose.yml for version 1 (the one I have in the machine where I'm going to test).

```
  orion:
    image: fiware/orion:2.0.0
    container_name: orion
    restart: always
    links:
      - mongo-orion
    ports:
      - "1026:1026"
    command: -corsOrigin __ALL -corsMaxAge 600 -dbhost mongo-orion

  iotagent-json:
    image: fiware/iotagent-json:1.8.0
    container_name: iotagent-json
    restart: always
    links:
      - mongo-orion
      - orion
    ports:
      - "4041:4041"
      - "7896:7896"
    environment:
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_LOG_LEVEL=DEBUG"
      - "IOTA_TIMESTAMP=true"
      - "IOTA_MONGO_HOST=mongo-orion"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagent-json"
      - "IOTA_HTTP_PORT=7896"
      - "IOTA_PROVIDER_URL=http://iotagent-json:4041"

  mongo-orion:
    image: mongo:3.4
    container_name: mongo-orion
    restart: always
    ports:
      - "27017:27017"

```
