### ISSUE TITLE
 NGSIv2 Notifications not including the Fiware-Service header for sth comet

### ISSUE THREAD

**Issue by Siedlerchr** [telefonicaid/fiware-orion#3540]
I stumbled across a bug which prevents me from creating a STH comet subscription. The issuie is similar to the old NGSIv1 related issue #2584 
I am trying to create a subscription for STH comet with the NGSIv2 subscription format using
NGSIv2 legacy attributes.
STH-Comet version 2.6.0 and orion 2.2.0.
I created the minimal setup without cygnus.
Both are running from docker on the same server and are accessible from the outside.

```
requests with ERROR in the last 60s interval
time=2019-08-22T08:16:39.107Z | lvl=WARN | corr=n/a | trans=n/a | op=OPER_STH_SERVER_LOG | from=n/a | srv=n/a | subsrv=n/a | comp=STH | msg=error=child "fiware-service" fails because [fiware-service is required]
time=2019-08-22T08:16:39.109Z | lvl=WARN | corr=2a5b5150-c4b5-11e9-be70-0242ac120105 | trans=fdef8685-5a63-4012-a88d-73bc836b2e68 | op=OPER_STH_POST | from=n/a | srv=n/a | subsrv=/ | comp=STH | msg=POST /notify, event={"request":"1566461799088:sth-comet:15:jzl0yeny:10001","timestamp":1566461799108,"tags":["validation","error","headers"],"data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"error=child \"fiware-service\" fails because [fiware-service is required]","validation":{"source":"headers","keys":[]}},"headers":{}}},"internal":true}

```
It neither works when I pass the fiware-service header and fiware-service, it doesn't matter if it's present or not.

```
curl -X POST \
  http://example.com:1026/v2/subscriptions/ \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: something' \
  -H 'fiware-servicepath: /' \
  -d '{
  "description": "Notify STH-Comet of all water level changes",
  "subject": {
    "entities": [
      {
        "idPattern": "WaterLevel.*"
      }
    ],
    "condition": {
      "attrs": [
      	"waterLevel"
      ]
    }
  },
  "notification": {
    "http": {
      "url": "http://example.com:8666/notify"
    },
    "attrs": [
      "waterLevel"
    ],
    "attrsFormat": "legacy"
  }
}'
```

**Comment by fgalan** [comment]
It would be great to know exactly which notification is Orion sending to STH. In order to do that just kill the STH process and start a listening process on the same port (e.g. `nc`).

**Comment by Siedlerchr** [comment]
First attempt without any addtional headers:
```

POST /notify HTTP/1.1
User-Agent: orion/2.2.0 libcurl/7.29.0
Host: example.com:8666
Fiware-Servicepath: /
Accept: application/json
Content-Length: 17181
Content-Type: application/json; charset=utf-8
Fiware-Correlator:  <GUID>
```
So the fiware-service-path is sent, but not the required `fiware-service` header.
 
When I add a 'fiware-service' header with value 'something' I don't receive any data. This is probaly because I don't have a fiware-service or service-path defined in orion.
When I supply and empty `fiware-service` header I have the same output as above.

**Comment by fgalan** [comment]
How Orion is running (i.e. `ps ax | grep contextBroker`)?

**Comment by Siedlerchr** [comment]
Inside a docker container:
```
/usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -dbhost mongo-db -logLevel ERROR -noCache -corsOrigin __ALL -reqMutexPolicy none
```

**Comment by fgalan** [comment]
Thanks for the information!

I can try to reproduce the case. You have provided me the curl you use to create the subscription and the way you run CB. Finally, could you provide me the update you are using to trigger notifications (in curl format), please?

**Comment by Siedlerchr** [comment]
Hi,
It's already the automatic initial notification after registering the subscription: 
1. Register the Subscription
2. Check with list all subscriptions, see lastSucess code 400 for the sth registration.
3. Run docker-logs fiware-sth-comet on the container image and see the error about the fiware service path.

I attached the relevant parts of the docker-compose files.

```yml
services:
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
#
#    ports:
#      - "27017:27017"
    networks:
      - default
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data
    restart: always

  orion:
    image: fiware/orion:2.2.0
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel ERROR -noCache -corsOrigin __ALL -reqMutexPolicy none
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
    restart: always

  sth-comet:
    image: fiware/sth-comet:2.6.0
    hostname: sth-comet
    container_name: fiware-sth-comet
    depends_on:
        - mongo-db
    networks:
        - default
    ports:
        - "8666:8666"
    environment:
        - STH_HOST=0.0.0.0
        - STH_PORT=8666
        - DB_PREFIX=sth_
        - DB_URI=mongo-db:27017
        - LOGOPS_LEVEL=DEBUG
    restart: always

volumes:
  mongo-db: ~
```
