### ISSUE TITLE
Run test in docker image

### ISSUE THREAD

**Issue by SamuelTJackson** [telefonicaid/fiware-orion#3628]
Hi,
I try to run the functional test in a docker container. 
Dockerfile:
```
FROM centos:centos7.6.1810

MAINTAINER FIWARE Orion Context Broker Team. Telefónica I+D

ENV ORION_USER orion
ENV GIT_REV_ORION master
ENV CLEAN_DEV_TOOLS 1

WORKDIR /opt

RUN \
    adduser --comment "${ORION_USER}" ${ORION_USER} && \
    # Install dependencies
    yum -y install epel-release && \
    yum -y install \
      boost-devel \
      bzip2 \
      cmake \
      gnutls-devel \
      libgcrypt-devel \
      libcurl-devel \
      openssl-devel \
      libuuid-devel \
      make \
      nc \
      git \
      gcc-c++ \
      scons \
      tar \
      which \
      cyrus-sasl-devel && \
    # Install libmicrohttpd from source
    curl -kOL http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.48.tar.gz && \
    tar xvf libmicrohttpd-0.9.48.tar.gz && \
    cd libmicrohttpd-0.9.48 && \
    ./configure --disable-messages --disable-postprocessor --disable-dauth && \
    make && \
    make install && \
    ldconfig && \
    # Install mongodb driver from source
    curl -kOL https://github.com/mongodb/mongo-cxx-driver/archive/legacy-1.1.2.tar.gz && \
    tar xfz legacy-1.1.2.tar.gz && \
    cd mongo-cxx-driver-legacy-1.1.2 && \
    scons --use-sasl-client --ssl && \
    scons install --prefix=/usr/local --use-sasl-client --ssl && \
    # Install rapidjson from source
    curl -kOL https://github.com/miloyip/rapidjson/archive/v1.0.2.tar.gz && \
    tar xfz v1.0.2.tar.gz && \
    mv rapidjson-1.0.2/include/rapidjson/ /usr/local/include && \
    # Install orion from source
    git clone https://github.com/telefonicaid/fiware-orion && \
    cd fiware-orion && \
    git checkout ${GIT_REV_ORION} && \
    make && \
    make install
RUN yum -y install python python-flask pyOpenSSL curl nc mongodb-org-shell valgrind bc lcov rpm-build
RUN mkdir ~/bin && export PATH=~/bin:$PATH
RUN cd /opt/libmicrohttpd-0.9.48/mongo-cxx-driver-legacy-1.1.2/fiware-orion && make install_scripts INSTALL_DIR=~ && bash ./scripts/testEnv.sh
WORKDIR /opt/libmicrohttpd-0.9.48/mongo-cxx-driver-legacy-1.1.2/fiware-orion
COPY ./entrypoint.sh .
RUN chmod a+x ./entrypoint.sh
```
entrypoint.sh:
```
#! /bin/bash
source ./scripts/testEnv.sh
printenv
make functional_test
```
docker-compose.yml:
```
version: '3.7'
services:
  mongo:
    image: mongo:3.6
    command: --nojournal
    container_name: mongo_test
    logging:
      driver: none
  orion:
    image: oriontest:latest
    container_name: orion_test
    environment:
      - CB_DATABASE_HOST=mongo
    links:
      - mongo
    command: ./entrypoint.sh
```
Every test fails with `FAIL 10 - SHELL-INIT produced output on stderr` 
Is it not possible to run the test in a container?
