### ISSUE TITLE
 MongoDB 4.x support

### ISSUE THREAD

**Issue by pinkerltm** [telefonicaid/fiware-orion#3781]
I am trying to connect orion to a MongoDB 4.2.6, all together deployed on Kubernetes (AKS). The convenient thing is, that there is already a Mongodb Community Operator for Kubernetes which deploys an production ready mongodb replicaset, BUT... as [Version 3.6 has End-of-life in April 2021](https://www.mongodb.com/support-policy) the [Operator only supports mongodb >4.0](https://github.com/mongodb/mongodb-kubernetes-operator/issues/256)

Are there any plans on supporting any 4.x Version. Currently Orion has problems to authenticate against mongo 4.2.6. As there isn`t any more information in the orion logfile of why this happens, I assume it is because of the version incompatibility.

**Comment by fgalan** [comment]
Yes, the plan is to upgrade the recommended version to MongoDB 4.2 (or even 4.4). This PR with the change has been around for a while and probably will be merged soon: https://github.com/telefonicaid/fiware-orion/pull/3732

However, regarding this:

> Orion has problems to authenticate against mongo 4.2.6

I wasn't aware of such problems. Could you provide more information on it, please? I mean, which exact problem, how to reproduce it, etc.

Thanks!

**Comment by kzangeli** [comment]
For Orion-LD I'm using mongo 4.0, 4.2 and 4.4.  Not seeing any problems whatsoever.
Please add some details of the errors you are seeing and we'll be able to fix it.

**Comment by pinkerltm** [comment]
This issue was really meant to clarifiy version compatibility. If it should work with 4.x then its ok and this issue can be closed.

As written above there isn't much info except an ERROR that orion wasn't able to authenticate (SCRAM-SHA1 is active on both sides, no SSL, admin database is available, admin user is there and I am able to connect via mongo CLI, the REPLICASET Name is "mongo")... 

I deployed orion with these arguments

```
- name: orion
        image: fiware/orion:2.4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 1026
        args: ["-dbhost", "mongo-svc:27017", "-logLevel", "DEBUG", "-rplSet", "mongo", "-dbuser", "admin", "-dbpwd", "123changeme", "-corsOrigin", "__ALL", "-corsMaxAge", "600", "-dbAuthDb", "admin"]
        ```
        
        I`ve tried it with a couple of other permutations of those arguments, i.e. without "dbAuthDb", all without success. I think this would be an issue on its own, should I create one?
        
        

> For Orion-LD I'm using mongo 4.0, 4.2 and 4.4. Not seeing any problems whatsoever.
> Please add some details of the errors you are seeing and we'll be able to fix it.

I also thought about migrating to Orion-LD but we already have a running service (in fact we were just moving to a bigger cluster when these problems appeared, and know I am backrolling to our older hand-crafted mongo 3.6 StatefulSet which also has issues). So long story short: I just don't want to introduce new sources for issues, mainly with our code which isn't fully LD ready/tested yet.
