### ISSUE TITLE
Authentication issue on MongoDB 4.2 replicaset

### ISSUE THREAD

**Issue by pinkerltm** [telefonicaid/fiware-orion#3782]
We are utilizing https://github.com/mongodb/mongodb-kubernetes-operator to get an production ready MongoDB 4.2.6 ReplicaSet up and running on kubernetes. In the same namespace "fiware" I am also deploying orion and trying to connect it to the created service, but the Log doesn't get very far 

```
time=Monday 22 Feb 13:48:31 2021.005Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[972]:main | msg=Orion Context Broker is running
time=Monday 22 Feb 13:48:31 2021.017Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[201]:mongoConnect | msg=Successful connection to database
time=Monday 22 Feb 13:48:31 2021.017Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[765]:setWriteConcern | msg=Database Operation Successful (setWriteConcern: 1)
time=Monday 22 Feb 13:48:31 2021.017Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[812]:getWriteConcern | msg=Database Operation Successful (getWriteConcern)
time=Monday 22 Feb 13:48:31 2021.019Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[869]:connectionAuth | msg=Database Startup Error (authentication fails: db=admin, username='admin', password='*****', mechanism='SCRAM-SHA-1', expection='Authentication failed.')
time=Monday 22 Feb 13:48:31 2021.019Z | lvl=FATAL | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=MongoGlobal.cpp[238]:mongoInit | msg=Fatal Error (MongoDB error)
```

We deploy Orion with the following manifest

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-deployment
  namespace: fiware
  labels:
    app: orion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion
  template:
    metadata:
      labels:
        app: orion
    spec:
      imagePullSecrets:
        - name: docker-msgis-net-cred
      containers:
      - name: orion
        image: fiware/orion:2.4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 1026
        args: ["-dbhost", "mongo-svc:27017", "-logLevel", "DEBUG", "-rplSet", "mongo", "-dbuser", "admin", "-dbpwd", "abc123changeme", "-corsOrigin", "__ALL", "-corsMaxAge", "600"]
        readinessProbe:
          httpGet:
            path: /version
            port: 1026
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /version
            port: 1026
          initialDelaySeconds: 15
          periodSeconds: 20
```

If I exec to one of the three mongo Contianers and try to connect (to the service) it works...

```
root@mongo-0:/# mongo -u admin -p abc123changeme mongo-svc:27017/admin 
MongoDB shell version v4.2.6
connecting to: mongodb://mongo-svc:27017/admin?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("5af0fe7d-7b90-4362-b839-76cb11b61bb5") }
MongoDB server version: 4.2.6
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
Server has startup warnings: 
2021-02-22T13:20:42.942+0000 I  CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2021-02-22T13:20:42.942+0000 I  CONTROL  [initandlisten] 
2021-02-22T13:20:42.942+0000 I  CONTROL  [initandlisten] 
2021-02-22T13:20:42.942+0000 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2021-02-22T13:20:42.942+0000 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
2021-02-22T13:20:42.942+0000 I  CONTROL  [initandlisten] 
---
Enable MongoDB's free cloud-based monitoring service, which will then receive and display
metrics about your deployment (disk utilization, CPU, operation statistics, etc).

The monitoring data will be available on a MongoDB website with a unique URL accessible to you
and anyone you share the URL with. MongoDB may use this information to make product
improvements and to suggest MongoDB products and deployment options to you.

To enable free monitoring, run the following command: db.enableFreeMonitoring()
To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---

mongo:PRIMARY> 
```

The replicaset is operational 

```
mongo:PRIMARY> rs.status()
{
        "set" : "mongo",
        "date" : ISODate("2021-02-22T13:54:53.640Z"),
        "myState" : 1,
        "term" : NumberLong(1),
        "syncingTo" : "",
        "syncSourceHost" : "",
        "syncSourceId" : -1,
        "heartbeatIntervalMillis" : NumberLong(2000),
        "majorityVoteCount" : 2,
        "writeMajorityCount" : 2,
        "optimes" : {
                "lastCommittedOpTime" : {
                        "ts" : Timestamp(1614002093, 1),
                        "t" : NumberLong(1)
                },
                "lastCommittedWallTime" : ISODate("2021-02-22T13:54:53.399Z"),
                "readConcernMajorityOpTime" : {
                        "ts" : Timestamp(1614002093, 1),
                        "t" : NumberLong(1)
                },
                "readConcernMajorityWallTime" : ISODate("2021-02-22T13:54:53.399Z"),
                "appliedOpTime" : {
                        "ts" : Timestamp(1614002093, 1),
                        "t" : NumberLong(1)
                },
                "durableOpTime" : {
                        "ts" : Timestamp(1614002093, 1),
                        "t" : NumberLong(1)
                },
                "lastAppliedWallTime" : ISODate("2021-02-22T13:54:53.399Z"),
                "lastDurableWallTime" : ISODate("2021-02-22T13:54:53.399Z")
        },
        "lastStableRecoveryTimestamp" : Timestamp(1614002063, 1),
        "lastStableCheckpointTimestamp" : Timestamp(1614002063, 1),
        "electionCandidateMetrics" : {
                "lastElectionReason" : "electionTimeout",
                "lastElectionDate" : ISODate("2021-02-22T13:22:12.976Z"),
                "electionTerm" : NumberLong(1),
                "lastCommittedOpTimeAtElection" : {
                        "ts" : Timestamp(0, 0),
                        "t" : NumberLong(-1)
                },
                "lastSeenOpTimeAtElection" : {
                        "ts" : Timestamp(1614000122, 1),
                        "t" : NumberLong(-1)
                },
                "numVotesNeeded" : 2,
                "priorityAtElection" : 1,
                "electionTimeoutMillis" : NumberLong(10000),
                "numCatchUpOps" : NumberLong(0),
                "newTermStartDate" : ISODate("2021-02-22T13:22:13.325Z"),
                "wMajorityWriteAvailabilityDate" : ISODate("2021-02-22T13:22:13.865Z")
        },
        "members" : [
                {
                        "_id" : 0,
                        "name" : "mongo-0.mongo-svc.fiware.svc.cluster.local:27017",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 2054,
                        "optime" : {
                                "ts" : Timestamp(1614002093, 1),
                                "t" : NumberLong(1)
                        },
                        "optimeDate" : ISODate("2021-02-22T13:54:53Z"),
                        "syncingTo" : "",
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "electionTime" : Timestamp(1614000133, 1),
                        "electionDate" : ISODate("2021-02-22T13:22:13Z"),
                        "configVersion" : 1,
                        "self" : true,
                        "lastHeartbeatMessage" : ""
                },
                {
                        "_id" : 1,
                        "name" : "mongo-1.mongo-svc.fiware.svc.cluster.local:27017",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 1970,
                        "optime" : {
                                "ts" : Timestamp(1614002093, 1),
                                "t" : NumberLong(1)
                        },
                        "optimeDurable" : {
                                "ts" : Timestamp(1614002093, 1),
                                "t" : NumberLong(1)
                        },
                        "optimeDate" : ISODate("2021-02-22T13:54:53Z"),
                        "optimeDurableDate" : ISODate("2021-02-22T13:54:53Z"),
                        "lastHeartbeat" : ISODate("2021-02-22T13:54:53.503Z"),
                        "lastHeartbeatRecv" : ISODate("2021-02-22T13:54:52.522Z"),
                        "pingMs" : NumberLong(0),
                        "lastHeartbeatMessage" : "",
                        "syncingTo" : "mongo-0.mongo-svc.fiware.svc.cluster.local:27017",
                        "syncSourceHost" : "mongo-0.mongo-svc.fiware.svc.cluster.local:27017",
                        "syncSourceId" : 0,
                        "infoMessage" : "",
                        "configVersion" : 1
                },
                {
                        "_id" : 2,
                        "name" : "mongo-2.mongo-svc.fiware.svc.cluster.local:27017",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 1970,
                        "optime" : {
                                "ts" : Timestamp(1614002093, 1),
                                "t" : NumberLong(1)
                        },
                        "optimeDurable" : {
                                "ts" : Timestamp(1614002093, 1),
                                "t" : NumberLong(1)
                        },
                        "optimeDate" : ISODate("2021-02-22T13:54:53Z"),
                        "optimeDurableDate" : ISODate("2021-02-22T13:54:53Z"),
                        "lastHeartbeat" : ISODate("2021-02-22T13:54:53.448Z"),
                        "lastHeartbeatRecv" : ISODate("2021-02-22T13:54:52.403Z"),
                        "pingMs" : NumberLong(0),
                        "lastHeartbeatMessage" : "",
                        "syncingTo" : "mongo-0.mongo-svc.fiware.svc.cluster.local:27017",
                        "syncSourceHost" : "mongo-0.mongo-svc.fiware.svc.cluster.local:27017",
                        "syncSourceId" : 0,
                        "infoMessage" : "",
                        "configVersion" : 1
                }
        ],
        "ok" : 1,
        "$clusterTime" : {
                "clusterTime" : Timestamp(1614002093, 1),
                "signature" : {
                        "hash" : BinData(0,"15jwvtz+3wrW65hGC97BFNq85Gc="),
                        "keyId" : NumberLong("6932077786974650371")
                }
        },
        "operationTime" : Timestamp(1614002093, 1)
}
mongo:PRIMARY> 
```

The Operator configures mongo instances on its own (I am not aware how exactly), nevertheless, I found only one possible conf File 

```
root@mongo-0:/# find / | grep mongod.conf
/etc/mongod.conf.orig
/data/automation-mongod.conf
root@mongo-0:/# cat /data/automation-mongod.conf 
net:
  bindIp: 0.0.0.0
  port: 27017
replication:
  replSetName: mongo
security:
  authorization: enabled
  keyFile: /var/lib/mongodb-mms-automation/authentication/keyfile
setParameter:
  authenticationMechanisms: SCRAM-SHA-256
storage:
  dbPath: /data
  wiredTiger:
    engineConfig:
      journalCompressor: zlib
root@mongo-0:/# 
```

**Comment by pinkerltm** [comment]
The cause of the problem is, that MongoDB Community Operator is constrained to SCRAM-SHA-256 whereas Orion only uses SCRAM-SHA-1...

There is a workaround to make MongoDB CO provide SCRAM-SHA-1 also, but this is only a proof-of-concept and doesn't work very reliably. The MongoDB guys are thinking that -256 is much safer and therefore should be used.

Are there any plans for Orion to make it configurable which SCRAM (exactly) someone wants to use? In fact you just have to pass the Argument instead of mapping SCRAM to SCRAM-SHA-1.

**Comment by fgalan** [comment]
Thanks for debugging on this!

The proposed change should be easy to do from the point of view of Orion code: the authentication mechanism is specified in the CLI as string and passed down to the `connectionAuth()` function, that uses it to compose the BSON parameter for the `auth()` function in the driver.

Maybe the current MongoDB driver used by Orion (which is legacy and deprecated) is not supporting it, but it seems the driver just passes along the method string. In order to check you can do a quick "hack" in the Orion code. Just find this line (in connectionOperations.cpp):

```
mongo::BSONObj params = BSON("mechanism" << mechanism << "user" << user << "db" << db << "pwd" << password);
```

and replace by:

```
mongo::BSONObj params = BSON("mechanism" << "SCRAM-SHA-256" << "user" << user << "db" << db << "pwd" << password);
```

Then build a docker image with that modification and test.

The result of your test will be very valuable towards a definitive fix of this in the Orion code.

**Comment by fgalan** [comment]
There is an experimental docker version available related with the driver migration to a new version (work in progress in PR #3622) which should support "SCRAM-SHA-256" in `-dbAuthMech`. Could you test it and tell us how it goes, please?

This is the image to use `telefonicaiot/fiware-orion:newdriver`.

Thanks for the feedback!

**Comment by fgalan** [comment]
> 
> 
> There is an experimental docker version available related with the driver migration to a new version (work in progress in PR #3622) which should support "SCRAM-SHA-256" in `-dbAuthMech`. Could you test it and tell us how it goes, please?
> 
> This is the image to use `telefonicaiot/fiware-orion:newdriver`
> 
> Thanks for the feedback!

Hold on... it seems there is some kind of problem with that image. I'll tell you when it gets ready again.

**Comment by fgalan** [comment]
> Hold on... it seems there is some kind of problem with that image. I'll tell you when it gets ready again.

Fixed. Now the image can be pulled and used. Sorry for the inconveniences.

**Comment by fgalan** [comment]
> There is an experimental docker version available related with the driver migration to a new version (work in progress in PR #3622) which should support "SCRAM-SHA-256" in `-dbAuthMech`. Could you test it and tell us how it goes, please?
> 
> This is the image to use `telefonicaiot/fiware-orion:newdriver`
> 
> Thanks for the feedback!

@pinkerltm any news in the test I suggested you to do, please?

**Comment by fgalan** [comment]
> This is the image to use telefonicaiot/fiware-orion:newdriver

PR #3622 has been merged into master. Thus, we can use `:latest` from now on. In fact, `:newdriver` label will be removed from dockerhub.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/3622. Closing issue.

However, it will be great to have feedback from @pinkerltm to confirm it.

**Comment by pinkerltm** [comment]
@fgalan sorry, had no attention on this issue lately and was busy with many other things. I'll definitely test this as soon as possible...at the moment our workaround was deploying a single mongo pod and rely on with all the workload. That approach isn't production ready, so its on my task list anyway. Thanks and pls hold on...

**Comment by fgalan** [comment]
No problem!

Just a comment: if you can, it's better to use MongoDB 4.4 instead of MongoDB 4.2 (the references version used by Orion has moved to 4.4 in Orion 3.0.0).

**Comment by pinkerltm** [comment]
@fgalan Recently we upgraded to `fiware/orion:3.0.0` and I also migrated back to our mongodb Community Operator for Kubernetes. Unfortunately I was only able to deploy a mongo 4.2.6 Cluster with it, not 4.4.x.

It seems that there is still a problem to connect to the mongodb cluster as I get the error message 

```
Error at querying MongoDB: not authorized on orion to execute command { find: &quot;entities&quot;, filter: {}, sort: { creDate: 1 }, limit: 20, skip: 0, $db: &quot;orion&quot;, lsid: { id: UUID&#40;&quot;aea30a21-4069-47b0-b47c-0604aacde904&quot;&#41; }, $clusterTime: { clusterTime: Timestamp&#40;1623320906, 1&#41;, signature: { hash: BinData&#40;0, 289C9A6D9DCB3A2756535BD95D34CF51AFCE7757&#41;, keyId: 6972089599224971267 } } 
```

It´s possible that I misconfigured the orion container though, so that it wasn't able to connect?

```YAML
containers:
      - name: orion
        image: fiware/orion:3.0.0 
        imagePullPolicy: Always
        ports:
        - containerPort: 1026
        args: [ "-dbhost", "mongo-svc:27017", "-logLevel", "DEBUG", "-rplSet", "mongo", "-dbuser", "admin", "-dbpwd", "abc123changeme", "-dbAuthMech", "SCRAM-SHA-256"]
```

I also tried without argument "dbAuthMech", without success also
