### ISSUE TITLE
fiware/orion:latest points to an old version (3.1.0-next)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#4028]
(Comes from https://github.com/telefonicaid/fiware-orion/issues/744)

> fiware-orion:latest shouldn't point to 3.1.0-next. It should point to latests commit in master branch. Could you provide more detail on how are you pulling and running this image, please?

At the present moment, being 525e91568a15e3864a7401ead1f23d0ca2ffaa29 the last commit at master (3.4.0-next version), I have done a quick test, with this docker-compose.yml, started with `docker-compose up`:

```
version: "3" 

services:
  orion:
    image: fiware/orion:latest
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbhost mongo

  mongo:
    image: mongo:4.4
    command: --nojournal
```

Then I get version on it:

```
$ curl localhost:1026/version
{
"orion" : {
  "version" : "3.1.0-next",
  "uptime" : "0 d, 0 h, 1 m, 15 s",
  "git_hash" : "7bd1e43514539bd65caeb30d4e3319202e0f115b",
  "compile_time" : "Mon Jul 26 08:19:44 UTC 2021",
  "compiled_by" : "root",
  "compiled_in" : "dae1c5e3a7d9",
  "release_date" : "Mon Jul 26 08:19:44 UTC 2021",
  "machine" : "x86_64",
  "doc" : "https://fiware-orion.rtfd.io/",
  "libversions": {
     "boost": "1_66",
     "libcurl": "libcurl/7.61.1 OpenSSL/1.1.1g zlib/1.2.11 nghttp2/1.33.0",
     "libmicrohttpd": "0.9.70",
     "openssl": "1.1",
     "rapidjson": "1.1.0",
     "mongoc": "1.17.4",
     "bson": "1.17.4"
  }
}
}
```

Which doesn't correspond to 3.4.0-next 525e91568a15e3864a7401ead1f23d0ca2ffaa29
