### ISSUE TITLE
ORION_REQ_TIMEOUT (and maybe other env vars) set to 0 show ERROR trace

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#4668]
Starting Orion this way:

We see:

```
$ ORION_REQ_TIMEOUT=0 contextBroker -fg -logLevel INFO
...
time=2025-04-23T08:36:05.571Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[977]:logEnvVars | msg=cannot show env var ORION_REQ_TIMEOUT (-reqTimeout) due to unrecognized type: 8
```

However the equivalent

```
contextBroker -fg -logLevel INFO -reqTimeout 0
```

doesn't show any error.

So probably there is some kind of problem with env var "translation" when value is 0.

**Comment by fgalan** [comment]
PR #4670

**Comment by fgalan** [comment]
It seems that when env vars are inyected using docker compose some problems occurs.

Testing with:

```
version: "3" 

services:
  orion:
    image: telefonicaiot/fiware-orion
    environment:
      - ORION_REQ_TIMEOUT=0
      - ORION_LOG_LEVEL=INFO
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbURI mongodb://mongo

  mongo:
    image: mongo:8.0
    command: --nojournal
```

we see

```
orion-1  | time=2025-04-24T08:25:10.183Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[973]:logEnvVars | msg=env var ORION_REQ_TIMEOUT (-reqTimeout): 4294967296
```
